// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 23 Sep 2016 15:58:43 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

#include "GLFW/glfw3.h"
#include "callbacks.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// GLFWglproc_ed6d6669 is a proxy for callback GLFWglproc.
void GLFWglproc_ed6d6669();

// GLFWvkproc_97c76b47 is a proxy for callback GLFWvkproc.
void GLFWvkproc_97c76b47();

// GLFWerrorfun_adb17582 is a proxy for callback GLFWerrorfun.
void GLFWerrorfun_adb17582(int arg0, char* arg1);

// GLFWwindowposfun_358cf663 is a proxy for callback GLFWwindowposfun.
void GLFWwindowposfun_358cf663(GLFWwindow* arg0, int arg1, int arg2);

// GLFWwindowsizefun_e3c4fd6a is a proxy for callback GLFWwindowsizefun.
void GLFWwindowsizefun_e3c4fd6a(GLFWwindow* arg0, int arg1, int arg2);

// GLFWwindowclosefun_e25779b2 is a proxy for callback GLFWwindowclosefun.
void GLFWwindowclosefun_e25779b2(GLFWwindow* arg0);

// GLFWwindowrefreshfun_9f26befc is a proxy for callback GLFWwindowrefreshfun.
void GLFWwindowrefreshfun_9f26befc(GLFWwindow* arg0);

// GLFWwindowfocusfun_16af50d3 is a proxy for callback GLFWwindowfocusfun.
void GLFWwindowfocusfun_16af50d3(GLFWwindow* arg0, int arg1);

// GLFWwindowiconifyfun_bb24b88b is a proxy for callback GLFWwindowiconifyfun.
void GLFWwindowiconifyfun_bb24b88b(GLFWwindow* arg0, int arg1);

// GLFWframebuffersizefun_ae059393 is a proxy for callback GLFWframebuffersizefun.
void GLFWframebuffersizefun_ae059393(GLFWwindow* arg0, int arg1, int arg2);

// GLFWmousebuttonfun_8e0aa0a is a proxy for callback GLFWmousebuttonfun.
void GLFWmousebuttonfun_8e0aa0a(GLFWwindow* arg0, int arg1, int arg2, int arg3);

// GLFWcursorposfun_39751795 is a proxy for callback GLFWcursorposfun.
void GLFWcursorposfun_39751795(GLFWwindow* arg0, double arg1, double arg2);

// GLFWcursorenterfun_6d33066c is a proxy for callback GLFWcursorenterfun.
void GLFWcursorenterfun_6d33066c(GLFWwindow* arg0, int arg1);

// GLFWscrollfun_13e3e5d1 is a proxy for callback GLFWscrollfun.
void GLFWscrollfun_13e3e5d1(GLFWwindow* arg0, double arg1, double arg2);

// GLFWkeyfun_3f040623 is a proxy for callback GLFWkeyfun.
void GLFWkeyfun_3f040623(GLFWwindow* arg0, int arg1, int arg2, int arg3, int arg4);

// GLFWcharfun_6d9c4127 is a proxy for callback GLFWcharfun.
void GLFWcharfun_6d9c4127(GLFWwindow* arg0, unsigned int arg1);

// GLFWcharmodsfun_a4666335 is a proxy for callback GLFWcharmodsfun.
void GLFWcharmodsfun_a4666335(GLFWwindow* arg0, unsigned int arg1, int arg2);

// GLFWdropfun_1f4f28be is a proxy for callback GLFWdropfun.
void GLFWdropfun_1f4f28be(GLFWwindow* arg0, int arg1, char** arg2);

// GLFWmonitorfun_de501d39 is a proxy for callback GLFWmonitorfun.
void GLFWmonitorfun_de501d39(GLFWmonitor* arg0, int arg1);

// GLFWjoystickfun_e5d73f5e is a proxy for callback GLFWjoystickfun.
void GLFWjoystickfun_e5d73f5e(int arg0, int arg1);

