// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 23 Sep 2016 17:19:09 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void GLFWglproc_ed6d6669() {
	glprocED6D6669();
}

void GLFWvkproc_97c76b47() {
	vkproc97C76B47();
}

void GLFWerrorfun_adb17582(int arg0, char* arg1) {
	errorFuncADB17582(arg0, arg1);
}

void GLFWwindowposfun_358cf663(GLFWwindow* arg0, int arg1, int arg2) {
	windowposFunc358CF663(arg0, arg1, arg2);
}

void GLFWwindowsizefun_e3c4fd6a(GLFWwindow* arg0, int arg1, int arg2) {
	windowsizeFuncE3C4FD6A(arg0, arg1, arg2);
}

void GLFWwindowclosefun_e25779b2(GLFWwindow* arg0) {
	windowcloseFuncE25779B2(arg0);
}

void GLFWwindowrefreshfun_9f26befc(GLFWwindow* arg0) {
	windowrefreshFunc9F26BEFC(arg0);
}

void GLFWwindowfocusfun_16af50d3(GLFWwindow* arg0, int arg1) {
	windowfocusFunc16AF50D3(arg0, arg1);
}

void GLFWwindowiconifyfun_bb24b88b(GLFWwindow* arg0, int arg1) {
	windowiconifyFuncBB24B88B(arg0, arg1);
}

void GLFWframebuffersizefun_ae059393(GLFWwindow* arg0, int arg1, int arg2) {
	framebuffersizeFuncAE059393(arg0, arg1, arg2);
}

void GLFWmousebuttonfun_8e0aa0a(GLFWwindow* arg0, int arg1, int arg2, int arg3) {
	mousebuttonFunc8E0AA0A(arg0, arg1, arg2, arg3);
}

void GLFWcursorposfun_39751795(GLFWwindow* arg0, double arg1, double arg2) {
	cursorposFunc39751795(arg0, arg1, arg2);
}

void GLFWcursorenterfun_6d33066c(GLFWwindow* arg0, int arg1) {
	cursorenterFunc6D33066C(arg0, arg1);
}

void GLFWscrollfun_13e3e5d1(GLFWwindow* arg0, double arg1, double arg2) {
	scrollFunc13E3E5D1(arg0, arg1, arg2);
}

void GLFWkeyfun_3f040623(GLFWwindow* arg0, int arg1, int arg2, int arg3, int arg4) {
	keyFunc3F040623(arg0, arg1, arg2, arg3, arg4);
}

void GLFWcharfun_6d9c4127(GLFWwindow* arg0, unsigned int arg1) {
	charFunc6D9C4127(arg0, arg1);
}

void GLFWcharmodsfun_a4666335(GLFWwindow* arg0, unsigned int arg1, int arg2) {
	charmodsFuncA4666335(arg0, arg1, arg2);
}

void GLFWdropfun_1f4f28be(GLFWwindow* arg0, int arg1, char** arg2) {
	dropFunc1F4F28BE(arg0, arg1, arg2);
}

void GLFWmonitorfun_de501d39(GLFWmonitor* arg0, int arg1) {
	monitorFuncDE501D39(arg0, arg1);
}

void GLFWjoystickfun_e5d73f5e(int arg0, int arg1) {
	joystickFuncE5D73F5E(arg0, arg1);
}

