// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 23 Sep 2016 17:19:09 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

package glfw

/*
#cgo darwin LDFLAGS: -framework Cocoa -framework OpenGL -framework IOKit -framework CoreVideo -lglfw3
#cgo linux LDFLAGS: -lGL -lX11 -lXrandr -lXxf86vm -lXi -lXcursor -lm -lXinerama -ldl -lrt -lglfw3
#cgo windows LDFLAGS: -lopengl32 -lgdi32 -lglfw3
#cgo freebsd LDFLAGS: -lGL -lX11 -lXrandr -lXxf86vm -lXi -lXcursor -lm -lXinerama -lglfw3
#cgo darwin CFLAGS: -D_GLFW_COCOA -D_GLFW_USE_CHDIR -D_GLFW_USE_MENUBAR -D_GLFW_USE_RETINA -Wno-deprecated-declarations
#cgo linux,wayland CFLAGS: -D_GLFW_WAYLAND
#cgo linux,!wayland CFLAGS: -D_GLFW_X11
#cgo windows CFLAGS: -D_GLFW_WIN32
#cgo freebsd,wayland CFLAGS: -D_GLFW_WAYLAND -D_GLFW_HAS_DLOPEN
#cgo freebsd,!wayland CFLAGS: -D_GLFW_X11 -D_GLFW_HAS_GLXGETPROCADDRESSARB -D_GLFW_HAS_DLOPEN
#include "GLFW/glfw3.h"
#include "callbacks.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// VersionMajor as defined in GLFW/glfw3.h:218
	VersionMajor = 3
	// VersionMinor as defined in GLFW/glfw3.h:225
	VersionMinor = 2
	// VersionRevision as defined in GLFW/glfw3.h:232
	VersionRevision = 1
	// True as defined in GLFW/glfw3.h:243
	True = 1
	// False as defined in GLFW/glfw3.h:250
	False = 0
	// Release as defined in GLFW/glfw3.h:261
	Release = 0
	// Press as defined in GLFW/glfw3.h:268
	Press = 1
	// Repeat as defined in GLFW/glfw3.h:275
	Repeat = 2
	// KeyUnknown as defined in GLFW/glfw3.h:302
	KeyUnknown = -1
	// KeySpace as defined in GLFW/glfw3.h:305
	KeySpace = 32
	// KeyApostrophe as defined in GLFW/glfw3.h:306
	KeyApostrophe = 39
	// KeyComma as defined in GLFW/glfw3.h:307
	KeyComma = 44
	// KeyMinus as defined in GLFW/glfw3.h:308
	KeyMinus = 45
	// KeyPeriod as defined in GLFW/glfw3.h:309
	KeyPeriod = 46
	// KeySlash as defined in GLFW/glfw3.h:310
	KeySlash = 47
	// Key0 as defined in GLFW/glfw3.h:311
	Key0 = 48
	// Key1 as defined in GLFW/glfw3.h:312
	Key1 = 49
	// Key2 as defined in GLFW/glfw3.h:313
	Key2 = 50
	// Key3 as defined in GLFW/glfw3.h:314
	Key3 = 51
	// Key4 as defined in GLFW/glfw3.h:315
	Key4 = 52
	// Key5 as defined in GLFW/glfw3.h:316
	Key5 = 53
	// Key6 as defined in GLFW/glfw3.h:317
	Key6 = 54
	// Key7 as defined in GLFW/glfw3.h:318
	Key7 = 55
	// Key8 as defined in GLFW/glfw3.h:319
	Key8 = 56
	// Key9 as defined in GLFW/glfw3.h:320
	Key9 = 57
	// KeySemicolon as defined in GLFW/glfw3.h:321
	KeySemicolon = 59
	// KeyEqual as defined in GLFW/glfw3.h:322
	KeyEqual = 61
	// KeyA as defined in GLFW/glfw3.h:323
	KeyA = 65
	// KeyB as defined in GLFW/glfw3.h:324
	KeyB = 66
	// KeyC as defined in GLFW/glfw3.h:325
	KeyC = 67
	// KeyD as defined in GLFW/glfw3.h:326
	KeyD = 68
	// KeyE as defined in GLFW/glfw3.h:327
	KeyE = 69
	// KeyF as defined in GLFW/glfw3.h:328
	KeyF = 70
	// KeyG as defined in GLFW/glfw3.h:329
	KeyG = 71
	// KeyH as defined in GLFW/glfw3.h:330
	KeyH = 72
	// KeyI as defined in GLFW/glfw3.h:331
	KeyI = 73
	// KeyJ as defined in GLFW/glfw3.h:332
	KeyJ = 74
	// KeyK as defined in GLFW/glfw3.h:333
	KeyK = 75
	// KeyL as defined in GLFW/glfw3.h:334
	KeyL = 76
	// KeyM as defined in GLFW/glfw3.h:335
	KeyM = 77
	// KeyN as defined in GLFW/glfw3.h:336
	KeyN = 78
	// KeyO as defined in GLFW/glfw3.h:337
	KeyO = 79
	// KeyP as defined in GLFW/glfw3.h:338
	KeyP = 80
	// KeyQ as defined in GLFW/glfw3.h:339
	KeyQ = 81
	// KeyR as defined in GLFW/glfw3.h:340
	KeyR = 82
	// KeyS as defined in GLFW/glfw3.h:341
	KeyS = 83
	// KeyT as defined in GLFW/glfw3.h:342
	KeyT = 84
	// KeyU as defined in GLFW/glfw3.h:343
	KeyU = 85
	// KeyV as defined in GLFW/glfw3.h:344
	KeyV = 86
	// KeyW as defined in GLFW/glfw3.h:345
	KeyW = 87
	// KeyX as defined in GLFW/glfw3.h:346
	KeyX = 88
	// KeyY as defined in GLFW/glfw3.h:347
	KeyY = 89
	// KeyZ as defined in GLFW/glfw3.h:348
	KeyZ = 90
	// KeyLeftBracket as defined in GLFW/glfw3.h:349
	KeyLeftBracket = 91
	// KeyBackslash as defined in GLFW/glfw3.h:350
	KeyBackslash = 92
	// KeyRightBracket as defined in GLFW/glfw3.h:351
	KeyRightBracket = 93
	// KeyGraveAccent as defined in GLFW/glfw3.h:352
	KeyGraveAccent = 96
	// KeyWorld1 as defined in GLFW/glfw3.h:353
	KeyWorld1 = 161
	// KeyWorld2 as defined in GLFW/glfw3.h:354
	KeyWorld2 = 162
	// KeyEscape as defined in GLFW/glfw3.h:357
	KeyEscape = 256
	// KeyEnter as defined in GLFW/glfw3.h:358
	KeyEnter = 257
	// KeyTab as defined in GLFW/glfw3.h:359
	KeyTab = 258
	// KeyBackspace as defined in GLFW/glfw3.h:360
	KeyBackspace = 259
	// KeyInsert as defined in GLFW/glfw3.h:361
	KeyInsert = 260
	// KeyDelete as defined in GLFW/glfw3.h:362
	KeyDelete = 261
	// KeyRight as defined in GLFW/glfw3.h:363
	KeyRight = 262
	// KeyLeft as defined in GLFW/glfw3.h:364
	KeyLeft = 263
	// KeyDown as defined in GLFW/glfw3.h:365
	KeyDown = 264
	// KeyUp as defined in GLFW/glfw3.h:366
	KeyUp = 265
	// KeyPageUp as defined in GLFW/glfw3.h:367
	KeyPageUp = 266
	// KeyPageDown as defined in GLFW/glfw3.h:368
	KeyPageDown = 267
	// KeyHome as defined in GLFW/glfw3.h:369
	KeyHome = 268
	// KeyEnd as defined in GLFW/glfw3.h:370
	KeyEnd = 269
	// KeyCapsLock as defined in GLFW/glfw3.h:371
	KeyCapsLock = 280
	// KeyScrollLock as defined in GLFW/glfw3.h:372
	KeyScrollLock = 281
	// KeyNumLock as defined in GLFW/glfw3.h:373
	KeyNumLock = 282
	// KeyPrintScreen as defined in GLFW/glfw3.h:374
	KeyPrintScreen = 283
	// KeyPause as defined in GLFW/glfw3.h:375
	KeyPause = 284
	// KeyF1 as defined in GLFW/glfw3.h:376
	KeyF1 = 290
	// KeyF2 as defined in GLFW/glfw3.h:377
	KeyF2 = 291
	// KeyF3 as defined in GLFW/glfw3.h:378
	KeyF3 = 292
	// KeyF4 as defined in GLFW/glfw3.h:379
	KeyF4 = 293
	// KeyF5 as defined in GLFW/glfw3.h:380
	KeyF5 = 294
	// KeyF6 as defined in GLFW/glfw3.h:381
	KeyF6 = 295
	// KeyF7 as defined in GLFW/glfw3.h:382
	KeyF7 = 296
	// KeyF8 as defined in GLFW/glfw3.h:383
	KeyF8 = 297
	// KeyF9 as defined in GLFW/glfw3.h:384
	KeyF9 = 298
	// KeyF10 as defined in GLFW/glfw3.h:385
	KeyF10 = 299
	// KeyF11 as defined in GLFW/glfw3.h:386
	KeyF11 = 300
	// KeyF12 as defined in GLFW/glfw3.h:387
	KeyF12 = 301
	// KeyF13 as defined in GLFW/glfw3.h:388
	KeyF13 = 302
	// KeyF14 as defined in GLFW/glfw3.h:389
	KeyF14 = 303
	// KeyF15 as defined in GLFW/glfw3.h:390
	KeyF15 = 304
	// KeyF16 as defined in GLFW/glfw3.h:391
	KeyF16 = 305
	// KeyF17 as defined in GLFW/glfw3.h:392
	KeyF17 = 306
	// KeyF18 as defined in GLFW/glfw3.h:393
	KeyF18 = 307
	// KeyF19 as defined in GLFW/glfw3.h:394
	KeyF19 = 308
	// KeyF20 as defined in GLFW/glfw3.h:395
	KeyF20 = 309
	// KeyF21 as defined in GLFW/glfw3.h:396
	KeyF21 = 310
	// KeyF22 as defined in GLFW/glfw3.h:397
	KeyF22 = 311
	// KeyF23 as defined in GLFW/glfw3.h:398
	KeyF23 = 312
	// KeyF24 as defined in GLFW/glfw3.h:399
	KeyF24 = 313
	// KeyF25 as defined in GLFW/glfw3.h:400
	KeyF25 = 314
	// KeyKp0 as defined in GLFW/glfw3.h:401
	KeyKp0 = 320
	// KeyKp1 as defined in GLFW/glfw3.h:402
	KeyKp1 = 321
	// KeyKp2 as defined in GLFW/glfw3.h:403
	KeyKp2 = 322
	// KeyKp3 as defined in GLFW/glfw3.h:404
	KeyKp3 = 323
	// KeyKp4 as defined in GLFW/glfw3.h:405
	KeyKp4 = 324
	// KeyKp5 as defined in GLFW/glfw3.h:406
	KeyKp5 = 325
	// KeyKp6 as defined in GLFW/glfw3.h:407
	KeyKp6 = 326
	// KeyKp7 as defined in GLFW/glfw3.h:408
	KeyKp7 = 327
	// KeyKp8 as defined in GLFW/glfw3.h:409
	KeyKp8 = 328
	// KeyKp9 as defined in GLFW/glfw3.h:410
	KeyKp9 = 329
	// KeyKpDecimal as defined in GLFW/glfw3.h:411
	KeyKpDecimal = 330
	// KeyKpDivide as defined in GLFW/glfw3.h:412
	KeyKpDivide = 331
	// KeyKpMultiply as defined in GLFW/glfw3.h:413
	KeyKpMultiply = 332
	// KeyKpSubtract as defined in GLFW/glfw3.h:414
	KeyKpSubtract = 333
	// KeyKpAdd as defined in GLFW/glfw3.h:415
	KeyKpAdd = 334
	// KeyKpEnter as defined in GLFW/glfw3.h:416
	KeyKpEnter = 335
	// KeyKpEqual as defined in GLFW/glfw3.h:417
	KeyKpEqual = 336
	// KeyLeftShift as defined in GLFW/glfw3.h:418
	KeyLeftShift = 340
	// KeyLeftControl as defined in GLFW/glfw3.h:419
	KeyLeftControl = 341
	// KeyLeftAlt as defined in GLFW/glfw3.h:420
	KeyLeftAlt = 342
	// KeyLeftSuper as defined in GLFW/glfw3.h:421
	KeyLeftSuper = 343
	// KeyRightShift as defined in GLFW/glfw3.h:422
	KeyRightShift = 344
	// KeyRightControl as defined in GLFW/glfw3.h:423
	KeyRightControl = 345
	// KeyRightAlt as defined in GLFW/glfw3.h:424
	KeyRightAlt = 346
	// KeyRightSuper as defined in GLFW/glfw3.h:425
	KeyRightSuper = 347
	// KeyMenu as defined in GLFW/glfw3.h:426
	KeyMenu = 348
	// KeyLast as defined in GLFW/glfw3.h:428
	KeyLast = KeyMenu
	// ModShift as defined in GLFW/glfw3.h:441
	ModShift = 0x0001
	// ModControl as defined in GLFW/glfw3.h:444
	ModControl = 0x0002
	// ModAlt as defined in GLFW/glfw3.h:447
	ModAlt = 0x0004
	// ModSuper as defined in GLFW/glfw3.h:450
	ModSuper = 0x0008
	// MouseButton1 as defined in GLFW/glfw3.h:460
	MouseButton1 = 0
	// MouseButton2 as defined in GLFW/glfw3.h:461
	MouseButton2 = 1
	// MouseButton3 as defined in GLFW/glfw3.h:462
	MouseButton3 = 2
	// MouseButton4 as defined in GLFW/glfw3.h:463
	MouseButton4 = 3
	// MouseButton5 as defined in GLFW/glfw3.h:464
	MouseButton5 = 4
	// MouseButton6 as defined in GLFW/glfw3.h:465
	MouseButton6 = 5
	// MouseButton7 as defined in GLFW/glfw3.h:466
	MouseButton7 = 6
	// MouseButton8 as defined in GLFW/glfw3.h:467
	MouseButton8 = 7
	// MouseButtonLast as defined in GLFW/glfw3.h:468
	MouseButtonLast = MouseButton8
	// MouseButtonLeft as defined in GLFW/glfw3.h:469
	MouseButtonLeft = MouseButton1
	// MouseButtonRight as defined in GLFW/glfw3.h:470
	MouseButtonRight = MouseButton2
	// MouseButtonMiddle as defined in GLFW/glfw3.h:471
	MouseButtonMiddle = MouseButton3
	// Joystick1 as defined in GLFW/glfw3.h:480
	Joystick1 = 0
	// Joystick2 as defined in GLFW/glfw3.h:481
	Joystick2 = 1
	// Joystick3 as defined in GLFW/glfw3.h:482
	Joystick3 = 2
	// Joystick4 as defined in GLFW/glfw3.h:483
	Joystick4 = 3
	// Joystick5 as defined in GLFW/glfw3.h:484
	Joystick5 = 4
	// Joystick6 as defined in GLFW/glfw3.h:485
	Joystick6 = 5
	// Joystick7 as defined in GLFW/glfw3.h:486
	Joystick7 = 6
	// Joystick8 as defined in GLFW/glfw3.h:487
	Joystick8 = 7
	// Joystick9 as defined in GLFW/glfw3.h:488
	Joystick9 = 8
	// Joystick10 as defined in GLFW/glfw3.h:489
	Joystick10 = 9
	// Joystick11 as defined in GLFW/glfw3.h:490
	Joystick11 = 10
	// Joystick12 as defined in GLFW/glfw3.h:491
	Joystick12 = 11
	// Joystick13 as defined in GLFW/glfw3.h:492
	Joystick13 = 12
	// Joystick14 as defined in GLFW/glfw3.h:493
	Joystick14 = 13
	// Joystick15 as defined in GLFW/glfw3.h:494
	Joystick15 = 14
	// Joystick16 as defined in GLFW/glfw3.h:495
	Joystick16 = 15
	// JoystickLast as defined in GLFW/glfw3.h:496
	JoystickLast = Joystick16
	// NotInitialized as defined in GLFW/glfw3.h:513
	NotInitialized = 0x00010001
	// NoCurrentContext as defined in GLFW/glfw3.h:523
	NoCurrentContext = 0x00010002
	// InvalidEnum as defined in GLFW/glfw3.h:532
	InvalidEnum = 0x00010003
	// InvalidValue as defined in GLFW/glfw3.h:543
	InvalidValue = 0x00010004
	// OutOfMemory as defined in GLFW/glfw3.h:551
	OutOfMemory = 0x00010005
	// ApiUnavailable as defined in GLFW/glfw3.h:567
	ApiUnavailable = 0x00010006
	// VersionUnavailable as defined in GLFW/glfw3.h:584
	VersionUnavailable = 0x00010007
	// PlatformError as defined in GLFW/glfw3.h:595
	PlatformError = 0x00010008
	// FormatUnavailable as defined in GLFW/glfw3.h:614
	FormatUnavailable = 0x00010009
	// NoWindowContext as defined in GLFW/glfw3.h:622
	NoWindowContext = 0x0001000A
	// Focused as defined in GLFW/glfw3.h:625
	Focused = 0x00020001
	// Iconified as defined in GLFW/glfw3.h:626
	Iconified = 0x00020002
	// Resizable as defined in GLFW/glfw3.h:627
	Resizable = 0x00020003
	// Visible as defined in GLFW/glfw3.h:628
	Visible = 0x00020004
	// Decorated as defined in GLFW/glfw3.h:629
	Decorated = 0x00020005
	// AutoIconify as defined in GLFW/glfw3.h:630
	AutoIconify = 0x00020006
	// Floating as defined in GLFW/glfw3.h:631
	Floating = 0x00020007
	// Maximized as defined in GLFW/glfw3.h:632
	Maximized = 0x00020008
	// RedBits as defined in GLFW/glfw3.h:634
	RedBits = 0x00021001
	// GreenBits as defined in GLFW/glfw3.h:635
	GreenBits = 0x00021002
	// BlueBits as defined in GLFW/glfw3.h:636
	BlueBits = 0x00021003
	// AlphaBits as defined in GLFW/glfw3.h:637
	AlphaBits = 0x00021004
	// DepthBits as defined in GLFW/glfw3.h:638
	DepthBits = 0x00021005
	// StencilBits as defined in GLFW/glfw3.h:639
	StencilBits = 0x00021006
	// AccumRedBits as defined in GLFW/glfw3.h:640
	AccumRedBits = 0x00021007
	// AccumGreenBits as defined in GLFW/glfw3.h:641
	AccumGreenBits = 0x00021008
	// AccumBlueBits as defined in GLFW/glfw3.h:642
	AccumBlueBits = 0x00021009
	// AccumAlphaBits as defined in GLFW/glfw3.h:643
	AccumAlphaBits = 0x0002100A
	// AuxBuffers as defined in GLFW/glfw3.h:644
	AuxBuffers = 0x0002100B
	// Stereo as defined in GLFW/glfw3.h:645
	Stereo = 0x0002100C
	// Samples as defined in GLFW/glfw3.h:646
	Samples = 0x0002100D
	// SrgbCapable as defined in GLFW/glfw3.h:647
	SrgbCapable = 0x0002100E
	// RefreshRate as defined in GLFW/glfw3.h:648
	RefreshRate = 0x0002100F
	// Doublebuffer as defined in GLFW/glfw3.h:649
	Doublebuffer = 0x00021010
	// ClientApi as defined in GLFW/glfw3.h:651
	ClientApi = 0x00022001
	// ContextVersionMajor as defined in GLFW/glfw3.h:652
	ContextVersionMajor = 0x00022002
	// ContextVersionMinor as defined in GLFW/glfw3.h:653
	ContextVersionMinor = 0x00022003
	// ContextRevision as defined in GLFW/glfw3.h:654
	ContextRevision = 0x00022004
	// ContextRobustness as defined in GLFW/glfw3.h:655
	ContextRobustness = 0x00022005
	// OpenglForwardCompat as defined in GLFW/glfw3.h:656
	OpenglForwardCompat = 0x00022006
	// OpenglDebugContext as defined in GLFW/glfw3.h:657
	OpenglDebugContext = 0x00022007
	// OpenglProfile as defined in GLFW/glfw3.h:658
	OpenglProfile = 0x00022008
	// ContextReleaseBehavior as defined in GLFW/glfw3.h:659
	ContextReleaseBehavior = 0x00022009
	// ContextNoError as defined in GLFW/glfw3.h:660
	ContextNoError = 0x0002200A
	// ContextCreationApi as defined in GLFW/glfw3.h:661
	ContextCreationApi = 0x0002200B
	// NoApi as defined in GLFW/glfw3.h:663
	NoApi = 0
	// OpenglApi as defined in GLFW/glfw3.h:664
	OpenglApi = 0x00030001
	// OpenglEsApi as defined in GLFW/glfw3.h:665
	OpenglEsApi = 0x00030002
	// NoRobustness as defined in GLFW/glfw3.h:667
	NoRobustness = 0
	// NoResetNotification as defined in GLFW/glfw3.h:668
	NoResetNotification = 0x00031001
	// LoseContextOnReset as defined in GLFW/glfw3.h:669
	LoseContextOnReset = 0x00031002
	// OpenglAnyProfile as defined in GLFW/glfw3.h:671
	OpenglAnyProfile = 0
	// OpenglCoreProfile as defined in GLFW/glfw3.h:672
	OpenglCoreProfile = 0x00032001
	// OpenglCompatProfile as defined in GLFW/glfw3.h:673
	OpenglCompatProfile = 0x00032002
	// MouseCursor as defined in GLFW/glfw3.h:675
	MouseCursor = 0x00033001
	// StickyKeys as defined in GLFW/glfw3.h:676
	StickyKeys = 0x00033002
	// StickyMouseButtons as defined in GLFW/glfw3.h:677
	StickyMouseButtons = 0x00033003
	// CursorNormal as defined in GLFW/glfw3.h:679
	CursorNormal = 0x00034001
	// CursorHidden as defined in GLFW/glfw3.h:680
	CursorHidden = 0x00034002
	// CursorDisabled as defined in GLFW/glfw3.h:681
	CursorDisabled = 0x00034003
	// AnyReleaseBehavior as defined in GLFW/glfw3.h:683
	AnyReleaseBehavior = 0
	// ReleaseBehaviorFlush as defined in GLFW/glfw3.h:684
	ReleaseBehaviorFlush = 0x00035001
	// ReleaseBehaviorNone as defined in GLFW/glfw3.h:685
	ReleaseBehaviorNone = 0x00035002
	// NativeContextApi as defined in GLFW/glfw3.h:687
	NativeContextApi = 0x00036001
	// EglContextApi as defined in GLFW/glfw3.h:688
	EglContextApi = 0x00036002
	// ArrowMouseCursor as defined in GLFW/glfw3.h:701
	ArrowMouseCursor = 0x00036001
	// IbeamMouseCursor as defined in GLFW/glfw3.h:706
	IbeamMouseCursor = 0x00036002
	// CrosshairMouseCursor as defined in GLFW/glfw3.h:711
	CrosshairMouseCursor = 0x00036003
	// HandMouseCursor as defined in GLFW/glfw3.h:716
	HandMouseCursor = 0x00036004
	// HresizeMouseCursor as defined in GLFW/glfw3.h:721
	HresizeMouseCursor = 0x00036005
	// VresizeMouseCursor as defined in GLFW/glfw3.h:726
	VresizeMouseCursor = 0x00036006
	// Connected as defined in GLFW/glfw3.h:729
	Connected = 0x00040001
	// Disconnected as defined in GLFW/glfw3.h:730
	Disconnected = 0x00040002
	// DontCare as defined in GLFW/glfw3.h:732
	DontCare = -1
)
