// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 23 Sep 2016 17:19:09 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

/*
Package glfw provides Go bindings for multi-platform library for OpenGL, OpenGL ES and Vulkan development (http://glfw.org)
*/
package glfw
