// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 23 Sep 2016 15:58:43 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

/*
Package glfw provides Go bindings for the GLFW 3.2 API.
*/
package glfw
