// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 23 Sep 2016 17:19:09 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

package glfw

/*
#cgo darwin LDFLAGS: -framework Cocoa -framework OpenGL -framework IOKit -framework CoreVideo -lglfw3
#cgo linux LDFLAGS: -lGL -lX11 -lXrandr -lXxf86vm -lXi -lXcursor -lm -lXinerama -ldl -lrt -lglfw3
#cgo windows LDFLAGS: -lopengl32 -lgdi32 -lglfw3
#cgo freebsd LDFLAGS: -lGL -lX11 -lXrandr -lXxf86vm -lXi -lXcursor -lm -lXinerama -lglfw3
#cgo darwin CFLAGS: -D_GLFW_COCOA -D_GLFW_USE_CHDIR -D_GLFW_USE_MENUBAR -D_GLFW_USE_RETINA -Wno-deprecated-declarations
#cgo linux,wayland CFLAGS: -D_GLFW_WAYLAND
#cgo linux,!wayland CFLAGS: -D_GLFW_X11
#cgo windows CFLAGS: -D_GLFW_WIN32
#cgo freebsd,wayland CFLAGS: -D_GLFW_WAYLAND -D_GLFW_HAS_DLOPEN
#cgo freebsd,!wayland CFLAGS: -D_GLFW_X11 -D_GLFW_HAS_GLXGETPROCADDRESSARB -D_GLFW_HAS_DLOPEN
#include "GLFW/glfw3.h"
#include "callbacks.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Glproc type as declared in GLFW/glfw3.h:751
type Glproc func()

// Vkproc type as declared in GLFW/glfw3.h:765
type Vkproc func()

// Monitor as declared in GLFW/glfw3.h:777
type Monitor C.GLFWmonitor

// Window as declared in GLFW/glfw3.h:789
type Window C.GLFWwindow

// Cursor as declared in GLFW/glfw3.h:801
type Cursor C.GLFWcursor

// ErrorFunc type as declared in GLFW/glfw3.h:817
type ErrorFunc func(arg0 int32, arg1 string)

// WindowposFunc type as declared in GLFW/glfw3.h:836
type WindowposFunc func(arg0 []Window, arg1 int32, arg2 int32)

// WindowsizeFunc type as declared in GLFW/glfw3.h:854
type WindowsizeFunc func(arg0 []Window, arg1 int32, arg2 int32)

// WindowcloseFunc type as declared in GLFW/glfw3.h:870
type WindowcloseFunc func(arg0 []Window)

// WindowrefreshFunc type as declared in GLFW/glfw3.h:886
type WindowrefreshFunc func(arg0 []Window)

// WindowfocusFunc type as declared in GLFW/glfw3.h:903
type WindowfocusFunc func(arg0 []Window, arg1 int32)

// WindowiconifyFunc type as declared in GLFW/glfw3.h:921
type WindowiconifyFunc func(arg0 []Window, arg1 int32)

// FramebuffersizeFunc type as declared in GLFW/glfw3.h:939
type FramebuffersizeFunc func(arg0 []Window, arg1 int32, arg2 int32)

// MousebuttonFunc type as declared in GLFW/glfw3.h:960
type MousebuttonFunc func(arg0 []Window, arg1 int32, arg2 int32, arg3 int32)

// CursorposFunc type as declared in GLFW/glfw3.h:979
type CursorposFunc func(arg0 []Window, arg1 float64, arg2 float64)

// CursorenterFunc type as declared in GLFW/glfw3.h:996
type CursorenterFunc func(arg0 []Window, arg1 int32)

// ScrollFunc type as declared in GLFW/glfw3.h:1013
type ScrollFunc func(arg0 []Window, arg1 float64, arg2 float64)

// KeyFunc type as declared in GLFW/glfw3.h:1034
type KeyFunc func(arg0 []Window, arg1 int32, arg2 int32, arg3 int32, arg4 int32)

// CharFunc type as declared in GLFW/glfw3.h:1051
type CharFunc func(arg0 []Window, arg1 uint32)

// CharmodsFunc type as declared in GLFW/glfw3.h:1072
type CharmodsFunc func(arg0 []Window, arg1 uint32, arg2 int32)

// DropFunc type as declared in GLFW/glfw3.h:1089
type DropFunc func(arg0 []Window, arg1 int32, arg2 []string)

// MonitorFunc type as declared in GLFW/glfw3.h:1105
type MonitorFunc func(arg0 []Monitor, arg1 int32)

// JoystickFunc type as declared in GLFW/glfw3.h:1122
type JoystickFunc func(arg0 int32, arg1 int32)

// Vidmode as declared in GLFW/glfw3.h:1156
type Vidmode struct {
	Width          int32
	Height         int32
	RedBits        int32
	GreenBits      int32
	BlueBits       int32
	RefreshRate    int32
	ref98662845    *C.GLFWvidmode
	allocs98662845 interface{}
}

// Gammaramp as declared in GLFW/glfw3.h:1183
type Gammaramp struct {
	Red            []uint16
	Green          []uint16
	Blue           []uint16
	Size           uint32
	ref49b9eb5f    *C.GLFWgammaramp
	allocs49b9eb5f interface{}
}

// Image as declared in GLFW/glfw3.h:1204
type Image struct {
	Width          int32
	Height         int32
	Pixels         []byte
	ref1787268c    *C.GLFWimage
	allocs1787268c interface{}
}
